version: "3"

services:
  mongo:
    ports:
      - 27017:27017
  redis:
    ports:
      - 6379:6379
  graphql:
    command: pm2-dev process.yml
  web:
    ports:
      - 3000:3000
    command: npm run start
