version: "3.7"

services:
  mongo:
    ports:
      - 27017:27017
  redis:
    ports:
      - 6379:6379
  graphql:
    build:
      target: base
    command: pm2-dev process.yml
  web:
    build:
      target: base
    ports:
      - 3000:3000
    command: npm run start
